### ISSUE TITLE
logos not showing

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/template-workshop-webpage#32]
something's not working here. in config.toml we have
```
[extra]
...

logos = [
#   { name = "CodeRefinery", url = "https://coderefinery.org/", image = "coderefinery.png" },
    { name = "CodeRefinery", url = "https://coderefinery.org/", image = "coderefinery.png" }
]
```
and in templates/index.html we have:
```
      {% for logo in config.extra.logos %}
        <a href="{{ logo.url }}">
          <img src="{{ resize_image(path="logos/" ~ logo.image, height=260, op="fit_height") | safe }}"
               alt="logo"
               style="margin-top: 25px;">
        </a>
      {% endfor %}
```

But the logo doesn't render. Inspecting the page shows:
```
<img src="https://coderefinery.org/processed_images/56e78a6e64b1a71600.png" alt="logo" style="margin-top: 25px;">
```
why is it processed_images under coderefinery.org? This happens to work for the github and twitter icons at the bottom but not logos added to a workshop webpage repo

**Comment by wikfeldt** [comment]
@bast sorry for bothering but i thought you might be able to spot the problem in under a minute

**Comment by bast** [comment]
Looking ...

**Comment by wikfeldt** [comment]
i should add that it renders locally...

**Comment by bast** [comment]
I have also tested this only locally so maybe my suggestion was not good. But I will check it out now.

**Comment by bast** [comment]
I think this is the reason: https://github.com/coderefinery/template-workshop-webpage/blob/b2aed8c4c57c1525f2a455efc2b1664e975229b0/config.toml#L2

(I haven't verified this but am quite confident)

**Comment by bast** [comment]
We could make the code simpler if we assume that logos are accessible directly via internet. Then we could avoid serving them from the course website.

**Comment by wikfeldt** [comment]
yeah it's the base_url. I couldn't see it used anywhere but changing it works

**Comment by wikfeldt** [comment]
fixed now with new base_url
