### ISSUE TITLE
suggestion: dedicated 'helper' page

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/template-workshop-webpage#45]
instead of "improve this page", which is still good, but probably doesn't need to be a top-level link.

"helpers" isn't the right title, though.  I"m thinking "Volunteer" or "Help out" or something, then list the ways to do that, focusing on being a helper.  I would send this to people I want to sign up as exercise leaders.

**Comment by bast** [comment]
Good idea. I agree that "improve this page" can rather be a ribbon or a bit out of top leve.
