### ISSUE TITLE
Consecutive Zoom Meetings and multiple time zones

### ISSUE THREAD

**Issue by tpfau** [coderefinery/template-workshop-webpage#56]
Since it happened now:
If we have consecutive Zoom meetingsfor events with in which people from different time zones are involved, I think it would be good not to have them in the same zoom room. 
For example the Exercise Lead session directly before the install help session led to some people showing up for the exercise lead intro while they wanted to attend the installation help. This can feel awkward, especially if you join e.g. 4 minutes past start, when the "This is the Exercise Lead onboarding" info was already given, and we are now in a "Who-is-who" round, and everyone is asked to introduce themselves, which can feel kind of odd for someone who is looking for installation help. 

Of course, it has the advantage of getting people connected potentially, but I would prefer to keep the meetings separate.

**Comment by bast** [comment]
This got already fixed for the workshop that just finished. Same Zoom room but half an hour in between and sent to different audiences. It wasn't a problem this time anymore.
