### ISSUE TITLE
Time zones in announcements

### ISSUE THREAD

**Issue by tpfau** [coderefinery/template-workshop-webpage#57]
I'm not sure about the possibility of this however here is a suggestion:
Since we work over multiple time zones it would be good if there would be some way for web-page announcements to in general display the times of events in the local time zone of the user. This would help in people not showing up at wrong time, and I'm pretty sure, that a lot of people (like me) don't necessarily notice which time zone was indicated but only remember the time announced.

**Comment by frankier** [comment]
How about using this: https://www.webcomponents.org/element/time-elements ?

**Comment by tpfau** [comment]
That sounds great.

**Comment by bast** [comment]
That's really neat.
