### ISSUE TITLE
Schedule first?

### ISSUE THREAD

**Issue by frankier** [coderefinery/template-workshop-webpage#60]
People were struggling a bit to find the schedule from this page during the in-person. They were using the schedule to navigate to lessons from previous days in order to remember what they had learnt in the next days. One possibility would be to put the schedule as the first thing. This might be slightly confusing at the first thing you see, but I think people not looking for the schedule will more or less automatically scroll past it.

**Comment by bast** [comment]
Good suggestion. I will test it out and see how it looks.
